# Generated by Django 6.0.3 on 2026-04-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords e.g. dinosaurs, time travel, space'),
        ),
    ]
