# Generated by Django 6.0.3 on 2026-04-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_movie_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('JA', 'Japanese'), ('KO', 'Korean')], default='EN', max_length=2),
        ),
    ]
