import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'popcornpass.settings')
django.setup()

from store.models import Director, Genre, Decade, Movie
from django.utils.text import slugify

# ── Decades ───────────────────────────────────────────────────
decades_data = [
    ("1970s", 1970, 1979),
    ("1980s", 1980, 1989),
    ("1990s", 1990, 1999),
    ("2000s", 2000, 2009),
    ("2010s", 2010, 2019),
    ("2020s", 2020, 2029),
]

decades = {}
for name, start, end in decades_data:
    d, _ = Decade.objects.get_or_create(
        name=name,
        defaults={'slug': slugify(name), 'start_year': start, 'end_year': end}
    )
    decades[name] = d
    print(f"Decade: {name}")

# ── Genres ────────────────────────────────────────────────────
genres_data = [
    "Action", "Drama", "Comedy", "Horror",
    "Sci-Fi", "Thriller", "Animation", "Romance"
]

genres = {}
for name in genres_data:
    g, _ = Genre.objects.get_or_create(
        name=name,
        defaults={'slug': slugify(name)}
    )
    genres[name] = g
    print(f"Genre: {name}")

# ── Directors ─────────────────────────────────────────────────
directors_data = [
    "Christopher Nolan",
    "Steven Spielberg",
    "Quentin Tarantino",
    "Martin Scorsese",
    "Chris Columbus"
    "James Cameron",
    "Ridley Scott",
    "Tim Burton",
    "Wes Anderson",
    "Francis Ford Coppola",
    "Stanley Kubrick",
    "Alfred Hitchcock",
    "Robert Zemeckis",
    "David Fincher",
    "Clint Eastwood",
    "Sofia Coppola",
    "Greta Gerwig",
    "Jordan Peele",
    "Denis Villeneuve",
    "Hayao Miyazaki",
    "Bong Joon-ho",
    "Alfonso Cuaron",
    "Luc Besson",
    "Guy Ritchie",
]

directors = {}
for name in directors_data:
    d, _ = Director.objects.get_or_create(name=name)
    directors[name] = d
    print(f"Director: {name}")

# ── Movies ────────────────────────────────────────────────────
movies_data = [

    # ── ACTION ───────────────────────────────────────────────
    {
        "title": "The Dark Knight",
        "director": "Christopher Nolan",
        "genre": "Action",
        "decade": "2000s",
        "description": "When the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological tests of his ability to fight injustice.",
        "imdb_id": "tt0468569",
        "rental_price": "3.99",
        "stock": 25,
        "language": "EN",
        "studio": "Warner Bros.",
        "release_year": 2008,
        "runtime": 152,
        "featured": True,
        "keywords": "batman, joker, gotham, superhero, vigilante, crime, heath ledger",
    },
    {
        "title": "Die Hard",
        "director": "Clint Eastwood",
        "genre": "Action",
        "decade": "1980s",
        "description": "A New York cop tries to save his wife and several others taken hostage by German terrorists during a Christmas party.",
        "imdb_id": "tt0095016",
        "rental_price": "2.49",
        "stock": 20,
        "language": "EN",
        "studio": "20th Century Fox",
        "release_year": 1988,
        "runtime": 132,
        "featured": False,
        "keywords": "hostage, christmas, terrorist, new york, cop, skyscraper, bruce willis",
    },
    {
        "title": "Gladiator",
        "director": "Ridley Scott",
        "genre": "Action",
        "decade": "2000s",
        "description": "A former Roman general becomes a slave, then a gladiator, and seeks revenge against the corrupt emperor who murdered his family.",
        "imdb_id": "tt0172495",
        "rental_price": "3.49",
        "stock": 15,
        "language": "EN",
        "studio": "DreamWorks",
        "release_year": 2000,
        "runtime": 155,
        "featured": True,
        "keywords": "rome, gladiator, arena, revenge, emperor, russell crowe, ancient",
    },
    {
        "title": "The Matrix",
        "director": "Luc Besson",
        "genre": "Action",
        "decade": "1990s",
        "description": "A computer hacker learns the reality he lives in is a simulated one and joins a rebellion against the machines controlling it.",
        "imdb_id": "tt0133093",
        "rental_price": "3.49",
        "stock": 22,
        "language": "EN",
        "studio": "Warner Bros.",
        "release_year": 1999,
        "runtime": 136,
        "featured": True,
        "keywords": "simulation, virtual reality, hacker, neo, machines, bullet time, cyberpunk",
    },
    {
        "title": "Top Gun: Maverick",
        "director": "Guy Ritchie",
        "genre": "Action",
        "decade": "2020s",
        "description": "After 30 years, Maverick is still pushing the envelope as a top naval aviator, training a new generation of graduates.",
        "imdb_id": "tt1745960",
        "rental_price": "4.49",
        "stock": 30,
        "language": "EN",
        "studio": "Paramount Pictures",
        "release_year": 2022,
        "runtime": 131,
        "featured": True,
        "keywords": "fighter jet, navy, pilot, maverick, tom cruise, aviation, military",
    },
    {
        "title": "Raiders of the Lost Ark",
        "director": "Steven Spielberg",
        "genre": "Action",
        "decade": "1980s",
        "description": "Archaeologist Indiana Jones races against Nazi agents to find the Ark of the Covenant.",
        "imdb_id": "tt0082971",
        "rental_price": "2.99",
        "stock": 18,
        "language": "EN",
        "studio": "Paramount Pictures",
        "release_year": 1981,
        "runtime": 115,
        "featured": False,
        "keywords": "indiana jones, ark, nazis, adventure, archaeology, treasure, whip",
    },

    # ── DRAMA ────────────────────────────────────────────────
    {
        "title": "The Godfather",
        "director": "Francis Ford Coppola",
        "genre": "Drama",
        "decade": "1970s",
        "description": "The aging patriarch of an organized crime dynasty transfers control of his empire to his reluctant son.",
        "imdb_id": "tt0068646",
        "rental_price": "3.99",
        "stock": 20,
        "language": "EN",
        "studio": "Paramount Pictures",
        "release_year": 1972,
        "runtime": 175,
        "featured": True,
        "keywords": "mafia, family, crime, don, corleone, power, murder, sicily",
    },
    {
        "title": "Schindler's List",
        "director": "Steven Spielberg",
        "genre": "Drama",
        "decade": "1990s",
        "description": "In German-occupied Poland, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.",
        "imdb_id": "tt0108052",
        "rental_price": "2.99",
        "stock": 10,
        "language": "EN",
        "studio": "Universal Pictures",
        "release_year": 1993,
        "runtime": 195,
        "featured": True,
        "keywords": "holocaust, world war 2, jews, nazi, survival, history, black and white",
    },
    {
        "title": "Goodfellas",
        "director": "Martin Scorsese",
        "genre": "Drama",
        "decade": "1990s",
        "description": "Henry Hill and his life in the mob, covering his relationship with his wife Karen and mob partners Jimmy and Tommy.",
        "imdb_id": "tt0099685",
        "rental_price": "2.99",
        "stock": 14,
        "language": "EN",
        "studio": "Warner Bros.",
        "release_year": 1990,
        "runtime": 146,
        "featured": True,
        "keywords": "mafia, mob, gangster, crime, new york, organized crime, henry hill",
    },
    {
        "title": "Pulp Fiction",
        "director": "Quentin Tarantino",
        "genre": "Drama",
        "decade": "1990s",
        "description": "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
        "imdb_id": "tt0110912",
        "rental_price": "2.99",
        "stock": 15,
        "language": "EN",
        "studio": "Miramax",
        "release_year": 1994,
        "runtime": 154,
        "featured": True,
        "keywords": "hitman, gangster, crime, nonlinear, briefcase, diner, samuel jackson",
    },
    {
        "title": "Forrest Gump",
        "director": "Robert Zemeckis",
        "genre": "Drama",
        "decade": "1990s",
        "description": "The presidencies of Kennedy and Johnson, Vietnam, Watergate, and other historical events unfold from the perspective of an Alabama man.",
        "imdb_id": "tt0109830",
        "rental_price": "2.99",
        "stock": 25,
        "language": "EN",
        "studio": "Paramount Pictures",
        "release_year": 1994,
        "runtime": 142,
        "featured": True,
        "keywords": "life, chocolate box, vietnam, history, running, tom hanks, jenny",
    },
    {
        "title": "Fight Club",
        "director": "David Fincher",
        "genre": "Drama",
        "decade": "1990s",
        "description": "An insomniac office worker and a soap salesman build an underground fight club that evolves into something much more.",
        "imdb_id": "tt0137523",
        "rental_price": "3.49",
        "stock": 16,
        "language": "EN",
        "studio": "20th Century Fox",
        "release_year": 1999,
        "runtime": 139,
        "featured": False,
        "keywords": "fighting, identity, soap, underground, brad pitt, twist, anarchism",
    },
    {
        "title": "Oppenheimer",
        "director": "Christopher Nolan",
        "genre": "Drama",
        "decade": "2020s",
        "description": "The story of J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
        "imdb_id": "tt15398776",
        "rental_price": "4.99",
        "stock": 28,
        "language": "EN",
        "studio": "Universal Pictures",
        "release_year": 2023,
        "runtime": 180,
        "featured": True,
        "keywords": "atomic bomb, nuclear, manhattan project, world war 2, physics, scientist",
    },

    # ── COMEDY ───────────────────────────────────────────────
    {
        "title": "The Grand Budapest Hotel",
        "director": "Wes Anderson",
        "genre": "Comedy",
        "decade": "2010s",
        "description": "A writer encounters the owner of an aging European hotel and learns of his friendship with a young employee involved in the theft of a painting.",
        "imdb_id": "tt2278388",
        "rental_price": "2.99",
        "stock": 14,
        "language": "EN",
        "studio": "Fox Searchlight",
        "release_year": 2014,
        "runtime": 99,
        "featured": True,
        "keywords": "hotel, europe, concierge, murder, comedy, quirky, 1930s, pastry",
    },
    {
        "title": "The Wolf of Wall Street",
        "director": "Martin Scorsese",
        "genre": "Comedy",
        "decade": "2010s",
        "description": "Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker to his fall involving crime and corruption.",
        "imdb_id": "tt0993846",
        "rental_price": "3.49",
        "stock": 16,
        "language": "EN",
        "studio": "Paramount Pictures",
        "release_year": 2013,
        "runtime": 180,
        "featured": False,
        "keywords": "stocks, money, fraud, wall street, broker, drugs, greed, dicaprio",
    },
    {
        "title": "Home Alone",
        "director": "Chris Columbus",
        "genre": "Comedy",
        "decade": "1990s",
        "description": "An eight-year-old troublemaker is accidentally left behind when his family flies to France for Christmas vacation.",
        "imdb_id": "tt0099785",
        "rental_price": "2.49",
        "stock": 30,
        "language": "EN",
        "studio": "20th Century Fox",
        "release_year": 1990,
        "runtime": 103,
        "featured": False,
        "keywords": "christmas, kid, burglars, traps, alone, holiday, macaulay culkin",
    },
    {
        "title": "Superbad",
        "director": "Guy Ritchie",
        "genre": "Comedy",
        "decade": "2000s",
        "description": "Two co-dependent high school seniors make a pact to lose their virginity before going to different colleges.",
        "imdb_id": "tt0829482",
        "rental_price": "2.49",
        "stock": 18,
        "language": "EN",
        "studio": "Columbia Pictures",
        "release_year": 2007,
        "runtime": 113,
        "featured": False,
        "keywords": "high school, teens, party, alcohol, friendship, coming of age, seth rogen",
    },
    {
        "title": "Barbie",
        "director": "Greta Gerwig",
        "genre": "Comedy",
        "decade": "2020s",
        "description": "Barbie and Ken go on a journey of self-discovery after Barbie has a crisis in Barbieland.",
        "imdb_id": "tt1517268",
        "rental_price": "4.49",
        "stock": 35,
        "language": "EN",
        "studio": "Warner Bros.",
        "release_year": 2023,
        "runtime": 114,
        "featured": True,
        "keywords": "barbie, ken, doll, plastic, pink, self discovery, feminist, margot robbie",
    },
    {
        "title": "Groundhog Day",
        "director": "Alfonso Cuaron",
        "genre": "Comedy",
        "decade": "1990s",
        "description": "A cynical TV weatherman finds himself inexplicably living the same day over and over again.",
        "imdb_id": "tt0107048",
        "rental_price": "2.49",
        "stock": 14,
        "language": "EN",
        "studio": "Columbia Pictures",
        "release_year": 1993,
        "runtime": 101,
        "featured": False,
        "keywords": "time loop, repeat, day, bill murray, punxsutawney, change, stuck",
    },

    # ── HORROR ───────────────────────────────────────────────
    {
        "title": "It",
        "director": "Alfonso Cuaron",
        "genre": "Horror",
        "decade": "2010s",
        "description": "A shapeshifting monster taking the form of a clown terrorises the children of Derry, Maine.",
        "imdb_id": "tt1396484",
        "rental_price": "3.49",
        "stock": 12,
        "language": "EN",
        "studio": "Warner Bros.",
        "release_year": 2017,
        "runtime": 135,
        "featured": False,
        "keywords": "clown, pennywise, children, sewer, fear, monster, stephen king, derry",
    },
    {
        "title": "Get Out",
        "director": "Jordan Peele",
        "genre": "Horror",
        "decade": "2010s",
        "description": "A young African-American man visits his white girlfriend's family estate and uncovers a disturbing secret.",
        "imdb_id": "tt5052448",
        "rental_price": "3.49",
        "stock": 16,
        "language": "EN",
        "studio": "Universal Pictures",
        "release_year": 2017,
        "runtime": 104,
        "featured": True,
        "keywords": "race, racism, hypnosis, thriller, twist, social commentary, family secret",
    },
    {
        "title": "A Quiet Place",
        "director": "Jordan Peele",
        "genre": "Horror",
        "decade": "2010s",
        "description": "A family struggles to survive in a post-apocalyptic world inhabited by blind monsters with an acute sense of hearing.",
        "imdb_id": "tt6644200",
        "rental_price": "3.49",
        "stock": 14,
        "language": "EN",
        "studio": "Paramount Pictures",
        "release_year": 2018,
        "runtime": 90,
        "featured": False,
        "keywords": "silence, monsters, family, survival, deaf, sound, apocalypse",
    },
    {
        "title": "Hereditary",
        "director": "Jordan Peele",
        "genre": "Horror",
        "decade": "2010s",
        "description": "After the family matriarch passes away, a grieving family is haunted by increasing disturbing and mysterious occurrences.",
        "imdb_id": "tt7784604",
        "rental_price": "3.99",
        "stock": 10,
        "language": "EN",
        "studio": "A24",
        "release_year": 2018,
        "runtime": 127,
        "featured": False,
        "keywords": "cult, family, supernatural, grief, demon, ari aster, disturbing",
    },
    {
        "title": "The Exorcist",
        "director": "Stanley Kubrick",
        "genre": "Horror",
        "decade": "1970s",
        "description": "When a young girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her.",
        "imdb_id": "tt0070047",
        "rental_price": "2.49",
        "stock": 12,
        "language": "EN",
        "studio": "Warner Bros.",
        "release_year": 1973,
        "runtime": 122,
        "featured": False,
        "keywords": "possession, demon, exorcism, priest, girl, devil, catholic, classic horror",
    },
    {
        "title": "Us",
        "director": "Jordan Peele",
        "genre": "Horror",
        "decade": "2010s",
        "description": "A family's serene beach vacation turns to chaos when their doppelgangers appear and begin to terrorize them.",
        "imdb_id": "tt6857112",
        "rental_price": "3.49",
        "stock": 13,
        "language": "EN",
        "studio": "Universal Pictures",
        "release_year": 2019,
        "runtime": 116,
        "featured": False,
        "keywords": "doppelganger, shadow, clone, beach, scissors, family, jordan peele",
    },

    # ── SCI-FI ───────────────────────────────────────────────
    {
        "title": "Inception",
        "director": "Christopher Nolan",
        "genre": "Sci-Fi",
        "decade": "2010s",
        "description": "A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea into a CEO's mind.",
        "imdb_id": "tt1375666",
        "rental_price": "3.99",
        "stock": 20,
        "language": "EN",
        "studio": "Warner Bros.",
        "release_year": 2010,
        "runtime": 148,
        "featured": True,
        "keywords": "dreams, heist, mind, subconscious, layers, spinning top, dicaprio",
    },
    {
        "title": "Interstellar",
        "director": "Christopher Nolan",
        "genre": "Sci-Fi",
        "decade": "2010s",
        "description": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        "imdb_id": "tt0816692",
        "rental_price": "3.99",
        "stock": 18,
        "language": "EN",
        "studio": "Paramount Pictures",
        "release_year": 2014,
        "runtime": 169,
        "featured": True,
        "keywords": "space, black hole, time, gravity, wormhole, nasa, future, astronaut",
    },
    {
        "title": "Avatar",
        "director": "James Cameron",
        "genre": "Sci-Fi",
        "decade": "2000s",
        "description": "A paraplegic Marine on Pandora becomes torn between following his orders and protecting the world he feels is his home.",
        "imdb_id": "tt0499549",
        "rental_price": "3.99",
        "stock": 30,
        "language": "EN",
        "studio": "20th Century Fox",
        "release_year": 2009,
        "runtime": 162,
        "featured": True,
        "keywords": "aliens, pandora, nature, blue, unobtanium, future, military, navi",
    },
    {
        "title": "Jurassic Park",
        "director": "Steven Spielberg",
        "genre": "Sci-Fi",
        "decade": "1990s",
        "description": "A pragmatic paleontologist visits an almost complete theme park where cloned dinosaurs run loose after a power failure.",
        "imdb_id": "tt0107290",
        "rental_price": "2.49",
        "stock": 22,
        "language": "EN",
        "studio": "Universal Pictures",
        "release_year": 1993,
        "runtime": 127,
        "featured": True,
        "keywords": "dinosaurs, t-rex, raptor, island, dna, cloning, theme park, paleontologist",
    },
    {
        "title": "Blade Runner 2049",
        "director": "Denis Villeneuve",
        "genre": "Sci-Fi",
        "decade": "2010s",
        "description": "A young blade runner discovers a secret that leads him to track down former blade runner Rick Deckard.",
        "imdb_id": "tt1856101",
        "rental_price": "3.99",
        "stock": 14,
        "language": "EN",
        "studio": "Warner Bros.",
        "release_year": 2017,
        "runtime": 164,
        "featured": False,
        "keywords": "replicant, future, dystopia, artificial intelligence, los angeles, rain, neon",
    },
    {
        "title": "Dune",
        "director": "Denis Villeneuve",
        "genre": "Sci-Fi",
        "decade": "2020s",
        "description": "Paul Atreides, a brilliant and gifted young man, must travel to the most dangerous planet in the universe to ensure the future of his family.",
        "imdb_id": "tt1160419",
        "rental_price": "4.49",
        "stock": 25,
        "language": "EN",
        "studio": "Warner Bros.",
        "release_year": 2021,
        "runtime": 155,
        "featured": True,
        "keywords": "desert, spice, sandworm, empire, politics, prophecy, timothee chalamet",
    },
    {
        "title": "E.T. the Extra-Terrestrial",
        "director": "Steven Spielberg",
        "genre": "Sci-Fi",
        "decade": "1980s",
        "description": "A troubled child summons the courage to help a friendly alien escape Earth and return to his home world.",
        "imdb_id": "tt0083866",
        "rental_price": "2.49",
        "stock": 18,
        "language": "EN",
        "studio": "Universal Pictures",
        "release_year": 1982,
        "runtime": 115,
        "featured": False,
        "keywords": "alien, friendship, home, bicycle, phone home, kids, extraterrestrial, spielberg",
    },

    # ── THRILLER ─────────────────────────────────────────────
    {
        "title": "The Silence of the Lambs",
        "director": "Ridley Scott",
        "genre": "Thriller",
        "decade": "1990s",
        "description": "A young FBI cadet must receive the help of an incarcerated cannibal killer to catch another serial killer.",
        "imdb_id": "tt0102926",
        "rental_price": "2.99",
        "stock": 12,
        "language": "EN",
        "studio": "Orion Pictures",
        "release_year": 1991,
        "runtime": 118,
        "featured": False,
        "keywords": "serial killer, fbi, cannibal, hannibal, lecter, psychological, clarice",
    },
    {
        "title": "Gone Girl",
        "director": "David Fincher",
        "genre": "Thriller",
        "decade": "2010s",
        "description": "With his wife's sudden disappearance on their fifth wedding anniversary, a man becomes the prime suspect.",
        "imdb_id": "tt2267998",
        "rental_price": "3.49",
        "stock": 16,
        "language": "EN",
        "studio": "20th Century Fox",
        "release_year": 2014,
        "runtime": 149,
        "featured": False,
        "keywords": "missing, wife, marriage, suspect, media, twist, ben affleck, rosamund pike",
    },
    {
        "title": "Parasite",
        "director": "Bong Joon-ho",
        "genre": "Thriller",
        "decade": "2010s",
        "description": "A poor family schemes to become employed by a wealthy family by infiltrating their household and posing as unrelated, highly qualified individuals.",
        "imdb_id": "tt6751668",
        "rental_price": "3.99",
        "stock": 18,
        "language": "KO",
        "studio": "CJ Entertainment",
        "release_year": 2019,
        "runtime": 132,
        "featured": True,
        "keywords": "class, inequality, rich, poor, family, korean, twist, social commentary, oscar",
    },
    {
        "title": "Knives Out",
        "director": "Rian Johnson",
        "genre": "Thriller",
        "decade": "2010s",
        "description": "A detective investigates the death of a patriarch of an eccentric, combative family.",
        "imdb_id": "tt8946378",
        "rental_price": "3.49",
        "stock": 20,
        "language": "EN",
        "studio": "Lionsgate",
        "release_year": 2019,
        "runtime": 130,
        "featured": False,
        "keywords": "murder mystery, detective, family, inheritance, whodunit, daniel craig, twist",
    },
    {
        "title": "Rear Window",
        "director": "Alfred Hitchcock",
        "genre": "Thriller",
        "decade": "1950s",
        "description": "A wheelchair-bound photographer spies on his neighbours and suspects one of them committed a murder.",
        "imdb_id": "tt0047396",
        "rental_price": "2.49",
        "stock": 10,
        "language": "EN",
        "studio": "Paramount Pictures",
        "release_year": 1954,
        "runtime": 112,
        "featured": False,
        "keywords": "voyeur, window, murder, suspense, hitchcock, classic, jimmy stewart",
    },
    {
        "title": "Zodiac",
        "director": "David Fincher",
        "genre": "Thriller",
        "decade": "2000s",
        "description": "In the late 1960s, the Zodiac Killer terrorizes San Francisco while investigators and a cartoonist obsess over the clues.",
        "imdb_id": "tt0443706",
        "rental_price": "3.49",
        "stock": 12,
        "language": "EN",
        "studio": "Paramount Pictures",
        "release_year": 2007,
        "runtime": 157,
        "featured": False,
        "keywords": "zodiac, serial killer, detective, true crime, san francisco, cipher, newspaper",
    },

    # ── ANIMATION ────────────────────────────────────────────
    {
        "title": "Spirited Away",
        "director": "Hayao Miyazaki",
        "genre": "Animation",
        "decade": "2000s",
        "description": "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
        "imdb_id": "tt0245429",
        "rental_price": "3.49",
        "stock": 20,
        "language": "JA",
        "studio": "Studio Ghibli",
        "release_year": 2001,
        "runtime": 125,
        "featured": True,
        "keywords": "spirit, japan, anime, ghibli, miyazaki, magic, bath house, chihiro",
    },
    {
        "title": "Princess Mononoke",
        "director": "Hayao Miyazaki",
        "genre": "Animation",
        "decade": "1990s",
        "description": "On a journey to find the cure for a curse, a prince becomes embroiled in a struggle between the gods of a forest and the humans who consume its resources.",
        "imdb_id": "tt0119698",
        "rental_price": "3.49",
        "stock": 16,
        "language": "JA",
        "studio": "Studio Ghibli",
        "release_year": 1997,
        "runtime": 134,
        "featured": False,
        "keywords": "nature, forest, spirit, wolf, japan, anime, ghibli, environment, war",
    },
    {
        "title": "Toy Story",
        "director": "Alfonso Cuaron",
        "genre": "Animation",
        "decade": "1990s",
        "description": "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy.",
        "imdb_id": "tt0114709",
        "rental_price": "2.49",
        "stock": 28,
        "language": "EN",
        "studio": "Pixar",
        "release_year": 1995,
        "runtime": 81,
        "featured": True,
        "keywords": "toys, cowboy, spaceman, woody, buzz, pixar, friendship, kids, imagination",
    },
    {
        "title": "The Lion King",
        "director": "Alfonso Cuaron",
        "genre": "Animation",
        "decade": "1990s",
        "description": "Lion prince Simba and his father are adored by the kingdom but Simba's uncle Scar schemes to take the throne.",
        "imdb_id": "tt0110357",
        "rental_price": "2.49",
        "stock": 25,
        "language": "EN",
        "studio": "Walt Disney",
        "release_year": 1994,
        "runtime": 88,
        "featured": True,
        "keywords": "lion, africa, king, simba, scar, hakuna matata, pride rock, disney",
    },
    {
        "title": "Spider-Man: Into the Spider-Verse",
        "director": "Alfonso Cuaron",
        "genre": "Animation",
        "decade": "2010s",
        "description": "Teen Miles Morales becomes the Spider-Man of his universe and must help other Spider-People stop a threat.",
        "imdb_id": "tt4633694",
        "rental_price": "3.99",
        "stock": 22,
        "language": "EN",
        "studio": "Sony Pictures",
        "release_year": 2018,
        "runtime": 117,
        "featured": True,
        "keywords": "spiderman, miles morales, multiverse, comic, spider, superhero, animation, oscar",
    },
    {
        "title": "My Neighbor Totoro",
        "director": "Hayao Miyazaki",
        "genre": "Animation",
        "decade": "1980s",
        "description": "Two young girls in postwar rural Japan befriend a giant magical forest spirit called Totoro.",
        "imdb_id": "tt0096283",
        "rental_price": "2.99",
        "stock": 18,
        "language": "JA",
        "studio": "Studio Ghibli",
        "release_year": 1988,
        "runtime": 86,
        "featured": False,
        "keywords": "totoro, forest, spirit, ghibli, japan, children, magical, nature, sisters",
    },

    # ── ROMANCE ──────────────────────────────────────────────
    {
        "title": "Titanic",
        "director": "James Cameron",
        "genre": "Romance",
        "decade": "1990s",
        "description": "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
        "imdb_id": "tt0120338",
        "rental_price": "2.99",
        "stock": 20,
        "language": "EN",
        "studio": "Paramount Pictures",
        "release_year": 1997,
        "runtime": 194,
        "featured": True,
        "keywords": "ship, love, iceberg, ocean, sinking, rose, jack, 1912, disaster",
    },
    {
        "title": "Edward Scissorhands",
        "director": "Tim Burton",
        "genre": "Romance",
        "decade": "1990s",
        "description": "An artificial man with scissors for hands is taken in by a suburban family and falls in love with their teenage daughter.",
        "imdb_id": "tt0099487",
        "rental_price": "2.49",
        "stock": 10,
        "language": "EN",
        "studio": "20th Century Fox",
        "release_year": 1990,
        "runtime": 105,
        "featured": False,
        "keywords": "scissors, hands, artificial, suburban, love, fantasy, gothic, tim burton",
    },
    {
        "title": "La La Land",
        "director": "Greta Gerwig",
        "genre": "Romance",
        "decade": "2010s",
        "description": "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations.",
        "imdb_id": "tt3783958",
        "rental_price": "3.49",
        "stock": 18,
        "language": "EN",
        "studio": "Lionsgate",
        "release_year": 2016,
        "runtime": 128,
        "featured": True,
        "keywords": "jazz, music, los angeles, dreams, musical, ryan gosling, emma stone, dance",
    },
    {
        "title": "Notting Hill",
        "director": "Alfonso Cuaron",
        "genre": "Romance",
        "decade": "1990s",
        "description": "The life of a simple bookshop owner changes when he meets the most famous film star in the world.",
        "imdb_id": "tt0125439",
        "rental_price": "2.49",
        "stock": 16,
        "language": "EN",
        "studio": "Universal Pictures",
        "release_year": 1999,
        "runtime": 124,
        "featured": False,
        "keywords": "london, bookshop, celebrity, julia roberts, hugh grant, british, love, romance",
    },
    {
        "title": "The Notebook",
        "director": "Sofia Coppola",
        "genre": "Romance",
        "decade": "2000s",
        "description": "A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom, but they are soon separated by her family.",
        "imdb_id": "tt0332280",
        "rental_price": "2.49",
        "stock": 20,
        "language": "EN",
        "studio": "New Line Cinema",
        "release_year": 2004,
        "runtime": 123,
        "featured": False,
        "keywords": "love, memory, summer, ryan gosling, rachel mcadams, separation, old age, letters",
    },
    {
        "title": "Lost in Translation",
        "director": "Sofia Coppola",
        "genre": "Romance",
        "decade": "2000s",
        "description": "A faded movie star and a neglected young woman form an unlikely bond after crossing paths in Tokyo.",
        "imdb_id": "tt0335266",
        "rental_price": "3.49",
        "stock": 12,
        "language": "EN",
        "studio": "Focus Features",
        "release_year": 2003,
        "runtime": 102,
        "featured": False,
        "keywords": "tokyo, japan, loneliness, bill murray, scarlett johansson, connection, hotel",
    },
]

# ── Add 1950s decade if needed for Rear Window ────────────────
d_1950s, _ = Decade.objects.get_or_create(
    name="1950s",
    defaults={'slug': "1950s", 'start_year': 1950, 'end_year': 1959}
)
decades["1950s"] = d_1950s

# ── Also add Rian Johnson director ───────────────────────────
rj, _ = Director.objects.get_or_create(name="Rian Johnson")
directors["Rian Johnson"] = rj

added   = 0
skipped = 0

for data in movies_data:
    if Movie.objects.filter(imdb_id=data['imdb_id']).exists():
        print(f"Skipped (exists): {data['title']}")
        skipped += 1
        continue

    # Handle decade (some movies may use 1950s)
    decade_obj = decades.get(data['decade'])
    if not decade_obj:
        print(f"WARNING: Decade {data['decade']} not found for {data['title']}")
        continue

    Movie.objects.create(
        title        = data['title'],
        slug         = slugify(data['title']),
        director     = directors[data['director']],
        genre        = genres[data['genre']],
        decade       = decade_obj,
        description  = data['description'],
        imdb_id      = data['imdb_id'],
        rental_price = data['rental_price'],
        stock        = data['stock'],
        language     = data['language'],
        studio       = data['studio'],
        release_year = data['release_year'],
        runtime      = data['runtime'],
        featured     = data['featured'],
        keywords     = data['keywords'],
    )
    print(f"Added: {data['title']}")
    added += 1

print(f"\n✅ Done! Added {added} movies, skipped {skipped} existing.")
print(f"Total movies in DB: {Movie.objects.count()}")